### ISSUE TITLE
Fixtureとかで初期投稿データの準備（商品、口コミ）

### ISSUE THREAD

**Issue by HirokiTakenaka** [IshidaHIRO/SDD3#128]

**Comment by HirokiTakenaka** [comment]
テストデータやDB初期データの投入方法がシンプルになるかと思い、fixtureやseedの使用方法を調べました。

基本的にはfixtureはテストデータとして、seedはDB初期データとして使うという理解です。

fixtureについては、現状のテストコード内から直接データを追加する方法に対するメリットがあまり無いかなぁ、という印象です。
（テストケースごとに異なるデータをロードしようとする場合手順が少し増える）

seedについては、誰かが一度定義してしまえば全員で同じ初期データを共有出来るので良いと思います。
ですが、現状必ずしも全員で同じ初期データを前提とすることが無いと思うので現時点ではマストではないかなと。

現時点では実装はしませんので、下記の調査内容を参考にだけしてみてください。
（やった方良ければ実装します）

**Comment by HirokiTakenaka** [comment]
## fixturesの使い方

### 基本
* データファイル（yaml）の作成
* test/fixtures/items.yml

```
data01:
  shop: ファミマ
  category: 惣菜
  item: 惣菜
  name: 国産鶏のサラダチキン
  price: 239
  good: 0
  bad: 0

 data02:
  shop: セブン
  category: 惣菜
  item: 惣菜
  name: サラダチキン
  price: 198
  good: 0
  bad: 0
```

　※Railsでは定義したデータは、テスト実行時にデフォルトで全件読み込まれる

* テストコードからの呼び出し方
```
items(:data01).shop
```

 * 参考：[Railsのテストで初期データ投入をしてくれるFixtureのつかいかた](http://qiita.com/itkrt2y/items/ca34fea17fc7dde56b7a)


### テストケースごとに別のテストデータを使用したい場合

* 下記のように手順が増える
  * テストケースごとのサブディレクトリを作成
  * その中にテストデータファイル（yaml）を作成
  * テストコードでサブディレクトリのfixtureを読み込むよう指定  
* 参考：[Rails初心者がちょっと変わったことをやろうとして詰まったことまとめ](http://d.hatena.ne.jp/namutaka/20101031/1288535660)　の「サブディレクトリのFixtureをUnitTest中で使う」

### その他参考
* [Rails テスティングガイド](http://railsguides.jp/testing.html)
　→Railsテスト入門


## seedsの使い方
* seedsファイルに追加データ内容を記述
* db/seeds.rb
```
Item.create(:shop => 'ファミマ', :category => '惣菜', :item => '惣菜', :name => 'サラダチキン（ハーブ）', :price => 100, :good => 10, :bad => 20, :image => 'xxx.jpg')
Item.create(:shop => 'セブン', :category => '惣菜', :item => '惣菜', :name => 'セブンのサラダチキン', :price => 120, :good => 12, :bad => 15, :image => 'yyy.jpg')
```

* seedデータをロードするrakeコマンドを実行
```
rake db:seed
```

* 参考：[rake db:seedを使った初期データの投入](http://www.rubylife.jp/rails/model/index10.html)
